manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nicekeyboards
      url-base: https://github.com/nicekeyboards
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-nice-nano
      remote: nicekeyboards
      revision: main
      path: modules/hardware/nice-nano
  self:
    path: config
